datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Use NLB or ELB based on your needs
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  port: 80
  targetPort: 3000
  selector:
    app.kubernetes.io/name: "grafana"